import {
  AlignJustify,
  Check,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  Circle,
  CircleSlashed,
  Expand,
  Flag,
  HelpCircle,
  Home,
  Hourglass,
  Info,
  Instagram,
  Languages,
  Laptop,
  LayoutGrid,
  LayoutList,
  LucideProps,
  Map,
  Menu,
  Moon,
  Paintbrush2,
  Palette,
  Pipette,
  Slice,
  SlidersHorizontal,
  Star,
  SunMedium,
  Twitter,
  Unlink,
  Sword,
  Hammer,
  Cat,
  Book,
  Castle,
  MountainSnow,
  type Icon as LucideIcon,
} from 'lucide-react';

export type Icon = LucideIcon;

export const Icons = {
  sun: SunMedium,
  moon: Moon,
  laptop: Laptop,
  twitter: Twitter,
  instagram: Instagram,
  chevronLeft: ChevronLeft,
  chevronRight: ChevronRight,
  chevronUp: ChevronUp,
  chevronDown: ChevronDown,
  slidersHorizontal: SlidersHorizontal,
  info: Info,
  menu: Menu,
  layoutGrid: LayoutGrid,
  layoutList: LayoutList,
  expand: Expand,
  palette: Palette,
  pipette: Pipette,
  paintbrush2: Paintbrush2,
  circleSlashed: CircleSlashed,
  helpCircle: HelpCircle,
  map: Map,
  languages: Languages,
  unlink: Unlink,
  hourglass: Hourglass,
  home: Home,
  flag: Flag,
  star: Star,
  alignJustify: AlignJustify,
  circle: Circle,
  slice: Slice,
  check: Check,
  sword: Sword,
  hammer: Hammer,
  cat: Cat,
  book: Book,
  castle: Castle,
  mountainSnow: MountainSnow,
};
